Pipeline changes to bring consistency/benefits from Flow-IPC counterparty.  TODO: Add the other sanitizers.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,15 +1,18 @@
 name: Flow pipeline
 
+# TODO: Code reuse somehow versus Flow-IPC workflow counterpart file?  Could apply to major parts of this file.
+# The copy/pasting and "see comment in other file" types of comments are a bit unseemly.
+
 on:
   push:
     branches:
       - main
   pull_request:
     branches:
-      - main     
-  # To run a workflow manually, the workflow must be configured to run on the workflow_dispatch event.
+      - main
+  # To create the button that runs a workflow manually (has to be in `main` at least):
   workflow_dispatch:
-      
+
 jobs:
   doc:
     strategy:
@@ -21,23 +24,23 @@ jobs:
             version: 15
             c-path: /usr/bin/clang-15
             cpp-path: /usr/bin/clang++-15
-        build-config:
+        build-cfg:
           - id: release
             conan-profile-build-type: Release
             conan-preset: release
-          
+
     runs-on: ubuntu-22.04
 
     name: |
-      doc-${{ matrix.compiler.id }}-${{ matrix.build-config.id }}
-    
-    steps:   
-    - name: Checkout Flow repository
-      uses: actions/checkout@v4
-    
+      doc-${{ matrix.compiler.id }}-${{ matrix.build-cfg.id }}
+
+    steps:
     - name: Update available software list for apt-get
       run: sudo apt-get update
-    
+
+    - name: Checkout `flow` repository
+      uses: actions/checkout@v4
+
     - name: Install Flow dependencies (like Graphviz) with apt-get
       run: |
         sudo apt-get install -y graphviz
@@ -45,10 +48,10 @@ jobs:
     - name: Install the latest version of Conan which is less than 2
       run: |
         pip install "conan<2"
-      
+
     - name: Create Conan profile
       run: |
-        cat <<EOF > conan_profile   
+        cat <<EOF > conan_profile
         [settings]
         compiler = ${{ matrix.compiler.name }}
         compiler.version = ${{ matrix.compiler.version }}
@@ -56,11 +59,11 @@ jobs:
         compiler.libcxx = libstdc++11
         arch = x86_64
         os = Linux
-        build_type = ${{ matrix.build-config.conan-profile-build-type }}
+        build_type = ${{ matrix.build-cfg.conan-profile-build-type }}
 
         [conf]
         tools.build:compiler_executables = { "c": "${{ matrix.compiler.c-path }}", "cpp": "${{ matrix.compiler.cpp-path }}" }
-        tools.env.virtualenv:auto_use = True 
+        tools.env.virtualenv:auto_use = True
 
         [buildenv]
         CC = ${{ matrix.compiler.c-path }}
@@ -70,34 +73,31 @@ jobs:
         flow:build = False
         flow:doc = True
         EOF
-    
+
     - name: Install Flow dependencies (like Doxygen) with Conan using the profile
       run: |
-        conan install \
-          . \
-          --profile:build conan_profile \
-          --profile:host conan_profile \
-          --build missing
+        conan install . \
+          --profile:build conan_profile --profile:host conan_profile --build missing
 
     - name: Generate code documentation using Conan and Doxygen
       run: |
         conan build .
 
-    - name: Create documentation tarball (full, API-only, landing page)
+    - name: Create documentation tarball (full docs, API-only docs, landing page)
       run: |
-        cd $GITHUB_WORKSPACE/doc/flow_doc
-        $GITHUB_WORKSPACE/tools/doc/stage_generated_docs.sh $GITHUB_WORKSPACE/build/${{ matrix.build-config.conan-profile-build-type }}
-
-         # Save runner space.
+        cd ${{ github.workspace }}/doc/ipc_doc
+        ${{ github.workspace }}/tools/doc/stage_generated_docs.sh \
+          ${{ github.workspace }}/build/${{ matrix.build-cfg.conan-profile-build-type }}
+        # Save runner space.
         rm -rf generated
 
     - name: Upload documentation tarball
       uses: actions/upload-artifact@v3
       with:
-        name: flow-doc-${{ matrix.compiler.id }}-${{ matrix.build-config.id }}
+        name: flow-doc
         path: |
           ${{ github.workspace }}/doc/flow_doc.tgz
-  
+
   build:
     strategy:
       fail-fast: false
@@ -107,7 +107,7 @@ jobs:
             name: gcc
             version: 9
             c-path: /usr/bin/gcc-9
-            cpp-path: /usr/bin/g++-9  
+            cpp-path: /usr/bin/g++-9
           - id: gcc-10
             name: gcc
             version: 10
@@ -122,35 +122,39 @@ jobs:
             name: gcc
             version: 13
             c-path: /usr/bin/gcc-13
-            cpp-path: /usr/bin/g++-13        
+            cpp-path: /usr/bin/g++-13
           - id: clang-13
             name: clang
             version: 13
             c-path: /usr/bin/clang-13
-            cpp-path: /usr/bin/clang++-13  
+            cpp-path: /usr/bin/clang++-13
           - id: clang-15
             name: clang
             version: 15
             c-path: /usr/bin/clang-15
-            cpp-path: /usr/bin/clang++-15     
+            cpp-path: /usr/bin/clang++-15
           - id: clang-16
             name: clang
-            version: 16 
-            c-path: /usr/bin/clang-16 
+            version: 16
+            c-path: /usr/bin/clang-16
             cpp-path: /usr/bin/clang++-16
-            install: True      
-          - id: clang-17 
+            install: True
+          - id: clang-17
             name: clang
             version: 17
             c-path: /usr/bin/clang-17
             cpp-path: /usr/bin/clang++-17
-            install: True     
-        build-and-test-config:
+            install: True
+        build-test-cfg:
           - id: debug
-            conan-profile-build-type: Debug     
+            conan-profile-build-type: Debug
           - id: release
-            conan-profile-build-type: Release   
-          - id: relwithdebinfo-tsan 
+            conan-profile-build-type: Release
+          - id: relwithdebinfo
+            conan-profile-build-type: RelWithDebInfo
+          - id: minsizerel
+            conan-profile-build-type: MinSizeRel
+          - id: relwithdebinfo-tsan
             conan-profile-build-type: RelWithDebInfo
             conan-profile-custom-conf: |
               tools.build:cflags = [ "-fsanitize=thread" ]
@@ -158,89 +162,102 @@ jobs:
               tools.build:sharedlinkflags = [ "-fsanitize=thread" ]
               tools.build:exelinkflags = [ "-fsanitize=thread" ]
             conan-profile-custom-settings: |
-              compiler.sanitizer = thread   
-            conan-custom-settings-definitions: |
-              data['compiler']['gcc']['sanitizer'] = ['None', 'address', 'thread', 'memory', 'undefined-behavior']
-              data['compiler']['clang']['sanitizer'] = ['None', 'address', 'thread', 'memory', 'undefined-behavior']
-          - id: relwithdebinfo
-            conan-profile-build-type: RelWithDebInfo  
-          - id: minsizerel
-            conan-profile-build-type: MinSizeRel
-            
+              compiler.sanitizer = thread
+            conan-custom-settings-defs: |
+              data['compiler']['gcc']['sanitizer'] = ['None', 'address', 'thread', 'memory', 'undefined']
+              data['compiler']['clang']['sanitizer'] = ['None', 'address', 'thread', 'memory', 'undefined']
+            sanitizer-name: tsan
+
         exclude:
           - compiler:  { id: gcc-9 }
-            build-and-test-config: { id: relwithdebinfo-tsan }
+            build-test-cfg: { id: relwithdebinfo-tsan }
           - compiler:  { id: gcc-10 }
-            build-and-test-config: { id: relwithdebinfo-tsan }
+            build-test-cfg: { id: relwithdebinfo-tsan }
           - compiler:  { id: gcc-11 }
-            build-and-test-config: { id: relwithdebinfo-tsan }
+            build-test-cfg: { id: relwithdebinfo-tsan }
           - compiler:  { id: gcc-13 }
-            build-and-test-config: { id: relwithdebinfo-tsan }
-   
+            build-test-cfg: { id: relwithdebinfo-tsan }
+
+    # Not using ubuntu-latest, so as to avoid surprises with OS upgrades and such.
     runs-on: ubuntu-22.04
 
-    name: |
-      build-${{ matrix.compiler.id }}-${{ matrix.build-and-test-config.id }}
+    name: ${{ matrix.compiler.id }}-${{ matrix.build-test-cfg.id }}
 
-    env: 
+    env:
+      build-dir: ${{ github.workspace }}/build/${{ matrix.build-test-cfg.conan-profile-build-type }}
+      install-root-dir: ${{ github.workspace }}/install/${{ matrix.build-test-cfg.conan-profile-build-type }}
+      # (Unfortunately cannot refer to earlier-assigned `env.` entries within subsequent ones.)
+      install-dir: ${{ github.workspace }}/install/${{ matrix.build-test-cfg.conan-profile-build-type }}/usr/local
+      # For the remaining env entries please see comments in Flow-IPC workflow counterpart.  We use same techniques.
+      san-suppress-cfg-file: ${{ github.workspace }}/install/${{ matrix.build-test-cfg.conan-profile-build-type }}/usr/local/bin/san_suppressions.cfg
+      san-suppress-cfg-in-file1: sanitize/${{ matrix.build-test-cfg.sanitizer-name }}/suppressions_${{ matrix.compiler.name }}.cfg
+      san-suppress-cfg-in-file2: sanitize/${{ matrix.build-test-cfg.sanitizer-name }}/suppressions_${{ matrix.compiler.name }}_${{ matrix.compiler.version }}.cfg
       setup-tests-env: |
-        if [ "${{ matrix.build-and-test-config.id }}" = relwithdebinfo-tsan ]; then
-          export TSAN_OPTIONS="disable_coredump=0 second_deadlock_stack=1 suppressions=${{ github.workspace }}/src/sanitize/tsan/suppressions_${{ matrix.compiler.name }}.cfg"
+        if [ "${{ matrix.build-test-cfg.sanitizer-name }}" = tsan ]; then
+          export SAN_SUPP=1
+          export SAN_SUPP_CFG=${{ github.workspace }}/install/${{ matrix.build-test-cfg.conan-profile-build-type }}/usr/local/bin/san_suppressions.cfg
+          export TSAN_OPTIONS="disable_coredump=0 second_deadlock_stack=1 suppressions=$SAN_SUPP_CFG"
+          echo "TSAN_OPTIONS = [$TSAN_OPTIONS]."
         fi
-        
-    steps:   
-    - name: Checkout Flow repository
+        # TODO: Add more *SAN here.
+        if [ "$SAN_SUPP" != '' ]; then
+          echo 'Sanitizer [${{ matrix.build-test-cfg.sanitizer-name }}] suppressions cfg contents:'
+          echo '[[[ file--'
+          cat $SAN_SUPP_CFG
+          echo '--file ]]]'
+        fi
+
+    steps:
+    - name: Checkout `flow` repository
       uses: actions/checkout@v4
-    
+
     - name: Update available software list for apt-get
       run: sudo apt-get update
-    
+
     - name: Install clang compiler
-      if: |
-        matrix.compiler.install && matrix.compiler.name == 'clang'
+      if: matrix.compiler.install && (matrix.compiler.name == 'clang')
       run: |
         wget https://apt.llvm.org/llvm.sh
         chmod u+x llvm.sh
         sudo ./llvm.sh ${{ matrix.compiler.version }}
-  
-    - name: Install GCC compiler
-      if: |
-        matrix.compiler.install && matrix.compiler.name == 'gcc'
+
+    - name: Install gcc compiler
+      if: matrix.compiler.install && (matrix.compiler.name == 'gcc')
       run: |
         sudo apt-get install -y software-properties-common
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
         sudo apt-get update
         sudo apt-get install -y gcc-${{ matrix.compiler.version }} g++-${{ matrix.compiler.version }}
 
+    # We get highest 1.x, instead of 2+, essentially to stay even with the Flow-IPC pipeline (and its similar workflow
+    # file).  See explanation in that file.  The to-do there applies to us as well (both should be done
+    # at ~the same time).
     - name: Install the latest version of Conan which is less than 2
       run: |
         pip install "conan<2"
-    
+
     - name: Add custom settings for Conan packages
+      if: matrix.build-test-cfg.conan-custom-settings-defs
       run: |
         conan config init
-        
         pip install PyYAML
-
         CONAN_SETTINGS_PATH=$(conan config home)/settings.yml
-
         python -c "
+
         import yaml
 
         with open('$CONAN_SETTINGS_PATH', 'r') as file:
           data = yaml.safe_load(file)
-        
-        ${{ matrix.build-and-test-config.conan-custom-settings-definitions }}
-      
+
+        ${{ matrix.build-test-cfg.conan-custom-settings-defs }}
+
         with open('$CONAN_SETTINGS_PATH', 'w') as file:
           yaml.dump(data, file)
         "
-      if: |
-        matrix.build-and-test-config.conan-custom-settings-definitions
-        
+
     - name: Create Conan profile
       run: |
-        cat <<EOF > conan_profile   
+        cat <<'EOF' > conan_profile
         [settings]
         compiler = ${{ matrix.compiler.name }}
         compiler.version = ${{ matrix.compiler.version }}
@@ -249,13 +266,13 @@ jobs:
         compiler.libcxx = libstdc++11
         arch = x86_64
         os = Linux
-        build_type = ${{ matrix.build-and-test-config.conan-profile-build-type }}
-        ${{ matrix.build-and-test-config.conan-profile-custom-settings }}
-        
+        build_type = ${{ matrix.build-test-cfg.conan-profile-build-type }}
+        ${{ matrix.build-test-cfg.conan-profile-custom-settings }}
+
         [conf]
         tools.build:compiler_executables = {"c": "${{ matrix.compiler.c-path }}", "cpp": "${{ matrix.compiler.cpp-path }}"}
         tools.env.virtualenv:auto_use = True
-        ${{ matrix.build-and-test-config.conan-profile-custom-conf }}
+        ${{ matrix.build-test-cfg.conan-profile-custom-conf }}
 
         [buildenv]
         CC = ${{ matrix.compiler.c-path }}
@@ -265,29 +282,58 @@ jobs:
         flow:build = True
         flow:doc = False
         EOF
-    
+
     - name: Install Flow dependencies with Conan using the profile
       run: |
-        conan install \
-          . \
-          --profile:build conan_profile \
-          --profile:host conan_profile \
-          --build missing
-    
+        conan install . \
+          --profile:build conan_profile --profile:host conan_profile --build missing
+
     - name: Build library and demos/tests with Conan
       run: |
         conan build .
 
-    - name: Install targets with Makefile
+    - name: Install built targets with Makefile
       run: |
-        VERBOSE=1 make install \
-          --directory $GITHUB_WORKSPACE/build/${{ matrix.build-and-test-config.conan-profile-build-type }} \
-          DESTDIR=${{ github.workspace }}/install/${{ matrix.build-and-test-config.conan-profile-build-type }}
+        make install \
+          --directory ${{ env.build-dir }} DESTDIR=${{ env.install-root-dir }}
+        # Save runner space: blow away build dir after install.
+        rm -rf ${{ env.build-dir }}
 
-    - name: Run 'NetFlow echo' demo/test
+    # From now on use !cancelled() to try to run any test/demo that exists regardless
+    # of preceding failures if any.  Same-ish (always()) with the log-upload at the end.
+    # Worst-case they'll all fail in super-basic ways and immediately; no extra harm done.
+
+    # From now on save logs in install-dir/bin/logs.  They will be tarred up and uploaded
+    # as artifacts at the end.  Please see comments in Flow-IPC workflow counterpart.
+    # We use the same techniques and reasoning.  Those may seem overkill given the small number
+    # of tests/demos below and their small amount of output (as of this writing); but this can
+    # and will grow.  The techniques will still apply.
+
+    - name: Run 'NetFlow echo' test/demo
       run: |
-          ${{ env.setup-tests-env }}
-          cd ${{ github.workspace }}/install/${{ matrix.build-and-test-config.conan-profile-build-type }}/usr/local/bin
-          ./net_flow_echo_srv.exec 8888 localhost & 
-          sleep 1
-          ./net_flow_echo_cli.exec 1 127.0.01 8888 "Hello world!"
+        cd ${{ env.install-dir }}/bin
+        mkdir -p logs/net_flow_echo
+        SUPP_DIR_A=${{ github.workspace }}/src
+        { cat $SUPP_DIR_A/${{ env.san-suppress-cfg-in-file1 }} $SUPP_DIR_A/${{ env.san-suppress-cfg-in-file2 }} \
+            > ${{ env.san-suppress-cfg-file }} 2> /dev/null; } || true
+        ${{ env.setup-tests-env }}
+        ./net_flow_echo_srv.exec 8888 localhost &
+        sleep 1
+        ./net_flow_echo_cli.exec 1 127.0.01 8888 "Hello world!"
+        echo "Server will print exception due to SIGTERM interruption; that is fine."
+        kill `pidof $PWD/net_flow_echo_srv.exec`
+
+    - name: Package test/demo logs tarball
+      if: always()
+      run: |
+        cd ${{ env.install-dir }}/bin
+        tar cvzf logs.tgz logs
+        rm -rf logs # Save runner space.
+
+    - name: Upload test/demo logs (please inspect if failure(s) seen above)
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: flow-test-logs-${{ matrix.compiler.id }}-${{ matrix.build-test-cfg.id }}
+        path: |
+          ${{ env.install-dir }}/bin/logs.tgz
